# Site settings
author: Janan Akkad
title: 
header-img: img/home-bg.png
email: jananakkad@hotmail.co.uk
copyright_name: Janan Akkad
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  spacecat33

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
